services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniostorage
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker/data:/data
